---
  - name: bind the kubelet-bootstrap user to the system node-bootstrapper cluster role
    local_action: >
                 shell ssh {{ ctl0_ip }} 'kubectl create clusterrolebinding kubelet-bootstrap --clusterrole=system:node-bootstrapper --user=kubelet-bootstrap'
    ignore_errors: True
    tags:
      - worker

  - name: create directories kubelet kube-proxy kubernetes
    file: 
      path: /var/lib/{{ item }}
      state: directory
      mode: 0755
    with_items:
         - kubelet
         - kube-proxy
         - kubernetes
    tags:
      - worker

  - name: copy files  in proper place
    shell: cp /root/{{ item.src }} /var/lib/{{ item.dest }}/
    with_items:
         - { src: 'bootstrap.kubeconfig', dest: 'kubelet'}
         - { src: 'kube-proxy.kubeconfig', dest: 'kube-proxy'}
         - { src: 'ca.pem', dest: 'kubernetes'}
    tags:
      - worker
 
  - name: Install Docker
    shell: >
           service docker stop;
           wget https://get.docker.com/builds/Linux/x86_64/docker-1.12.6.tgz -O /root/docker-1.12.6.tgz;
           tar -xvf /root/docker-1.12.6.tgz;
           cp /root/docker/docker* /usr/bin/ ;
    tags:
      - worker  
 
  - name: Create the Docker systemd unit file     
    template:
      src: docker.service.j2
      dest: /etc/systemd/system/docker.service
    notify:
      - Start Docker deamon
    tags:
      - worker

  - name: create dir to Install the kubelet
    file:
      path: /opt/cni
      state: directory
      mode: 0755
    tags:
      - worker
  - name: download CNI plugin
    shell: >
           wget wget https://storage.googleapis.com/kubernetes-release/network-plugins/cni-amd64-0799f5732f2a11b329d9e3d51b9c8f2e3759f2ff.tar.gz \
           -O /root/cni-amd64-0799f5732f2a11b329d9e3d51b9c8f2e3759f2ff.tar.gz;
           tar -xvf /root/cni-amd64-0799f5732f2a11b329d9e3d51b9c8f2e3759f2ff.tar.gz -C /opt/cni
    tags:
      - worker
 
  - name: Download and install the Kubernetes worker binaries
    shell: > 
           wget https://storage.googleapis.com/kubernetes-release/release/v1.6.1/bin/linux/amd64/{{item}}  -O /usr/bin/{{item}};
           chmod 0755 /usr/bin/{{item}}
    with_items:
         - kubectl
         - kube-proxy
         - kubelet
    tags:
      - worker

  - name: Create the kubelet systemd unit file
    template:
      src: kubelet.service.j2
      dest: /etc/systemd/system/kubelet.service
    notify:
      - Start the kubelet service
    tags:
      - worker
         
  - name: Create the kube-proxy systemd unit file
    template:
      src: kube-proxy.service.j2
      dest: /etc/systemd/system/kube-proxy.service
    notify:
      - Start the kube-proxy service
    tags:
      - worker
