---
  - name: install  cfssl  binaries
    get_url:
      url: https://pkg.cfssl.org/R1.2/cfssl_linux-amd64
      dest: /usr/local/bin/cfssl
      mode: 755
    tags: 
      - localhost 
     
  - name: install  cfssljson binaries
    get_url:
      url: https://pkg.cfssl.org/R1.2/cfssljson_linux-amd64
      dest: /usr/local/bin/cfssljson
      mode: 755
    tags: 
      - localhost 

  - name: Set up a Certificate Authority ; will generate ca-key.pem and ca.pem files
    shell: >
           cd /etc/ansible/roles/setting_up_CA_TLS_Cert/files/;
           /usr/local/bin/cfssl gencert -initca ca-csr.json | /usr/local/bin/cfssljson -bare ca
    tags: 
      - localhost 

  - name: Generate client and server TLS certificates will generate admin-key.pem admin.pem
    shell: >
           cd /etc/ansible/roles/setting_up_CA_TLS_Cert/files/;
           /usr/local/bin/cfssl gencert  -ca=ca.pem -ca-key=ca-key.pem -config=ca-config.json -profile=kubernetes \
           admin-csr.json | /usr/local/bin/cfssljson -bare admin
    tags: 
      - localhost 

  - name: Create the kube-proxy client certificate will generate kube-proxy-key.pem kube-proxy.pem
    shell: >
          cd /etc/ansible/roles/setting_up_CA_TLS_Cert/files/;
          /usr/local/bin/cfssl gencert -ca=ca.pem -ca-key=ca-key.pem -config=ca-config.json -profile=kubernetes \
          kube-proxy-csr.json | /usr/local/bin/cfssljson -bare kube-proxy
    tags: 
      - localhost

  - name: copy kubernetes-csr.json from template to file directory
    template: 
      src: kubernetes-csr.j2
      dest: /etc/ansible/roles/setting_up_CA_TLS_Cert/files/kubernetes-csr.json 
      mode: 644 

  - name: Create the kubernetes server certificate  will generate kubernetes-key.pem kubernetes.pem
    shell: >
           cd /etc/ansible/roles/setting_up_CA_TLS_Cert/files/;
           /usr/local/bin/cfssl gencert -ca=ca.pem -ca-key=ca-key.pem -config=ca-config.json -profile=kubernetes \
           kubernetes-csr.json | /usr/local/bin/cfssljson -bare kubernetes
            
    tags: 
      - localhost 
   
