---
  - name: Distribute the TLS certificates on workers nodes
    copy: src={{ item }} dest=/root/{{ item }}
    with_items:
         - ca.pem
         - kube-proxy.pem
         - kube-proxy-key.pem
         - bootstrap.kubeconfig
         - kube-proxy.kubeconfig
    tags:
      - worker

     
  - name: Distribute the TLS certificates on controller nodes
    copy: src={{ item }} dest=/root/{{ item }}
    with_items:
         - ca.pem
         - ca-key.pem
         - kubernetes-key.pem
         - kubernetes.pem
         - token.csv
    tags:
      - controller
