---
  - name: Provision the etcd Cluster
    shell: >
           mkdir -p /etc/etcd/;
           cp /root/ca.pem /root/kubernetes-key.pem /root/kubernetes.pem /etc/etcd/;
    tags:
      - controller
 
  - name: Download and Install the etcd binaries
    shell: >
           wget https://github.com/coreos/etcd/releases/download/v3.1.4/etcd-v3.1.4-linux-amd64.tar.gz -O /root/etcd-v3.1.4-linux-amd64.tar.gz;
           tar -xvf /root/etcd-v3.1.4-linux-amd64.tar.gz;
           mv /root/etcd-v3.1.4-linux-amd64/etcd* /usr/bin/ ;
           mkdir -p /var/lib/etcd;
    tags:
      - controller

  - name: move it to the systemd system directory
    template:
      src: etcd_service.j2 
      dest: /etc/systemd/system/etcd.service 
    notify:
      - Start the etcd service
    tags:
      - controller 
  - name: restart etcd service
    service: name=etcd state=restarted 
